import time, sys, WordCore
from ColorSplash import *
from UniData import *

#Color options run at a fraction speed, set optimization to turn colors off (visual/performance)

def mail():
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print("@@@                                                                                              @@@")
    print("@@@                                                                                              @@@")
    print("@@@  @          @; `@@@@@@@  `@@@@@@@@ ;@      @; @@@@@@@@                                       @@@")
    print("@@@  @@        @@+ @@:::::@@ @@::::::: ;@      @; @:::::::                                       @@@")
    print("@@@  @@@      @@@+ @      ;@ @# @@@@@@ ;@      @; @::::::                                        @@@")
    print("@@@  @ @@    @@ @+ @::::::+@ @# @@@@@@ ;@      @; @@@@@@@@.          @@@@@@@@@@@@@@@@@@          @@@")
    print("@@@  @  @@  @@  @+ @@@@@@@@@ @#      @ ;@      @;        @#         ` @@@@@@@@@@@@@@@@           @@@")
    print("@@@  @   @@#@   @+ @      ;@ @#      @ ;@      @;        @#         @` #@@@@@@@@@@@@@  @         @@@")
    print("@@@  @    @@    @+ @      ;@ +@@@@@@@@  @@@@@@@@  @@@@@@@@`         @@: '@@@@@@@@@@@  @@         @@@")
    print("@@@                                                                 @@@' '@@@@@@@@@  @@@         @@@")
    print("@@@                                                                 @@@@' :@@@@@@@  @@@@         @@@")
    print("@@@                                                                 @@@@@# `@@@@@  @@@@@         @@@")
    print("@@@                                                                 @@@@@@   @@@  `@@@@@         @@@")
    print("@@@                                                                 @@@@@  @ `@ `@ `@@@@         @@@")
    print("@@@                    @;         #@  @@@@@@@. .@ :@                @@@@  @@@  `@@@  @@@         @@@")
    print("@@@                    @@:       +@@ @@:::::@@ .@ :@                @@@  @@@@@:@@@@@  @@         @@@")
    print("@@@                    @+@.     ;@+@ @+      @ .@ :@                @@  @@@@@@@@@@@@@  @         @@@")
    print("@@@                    @:;@`   :@.;@ @#::::::@ .@ :@                @  @@@@@@@@@@@@@@@           @@@")
    print("@@@                    @: +@` .@: ;@ @@@@@@@@@ .@ :@                 `@@@@@@@@@@@@@@@@@          @@@")
    print("@@@                    @:  +@`@:  ;@ @+      @ .@ :@                                             @@@")
    print("@@@                    @:   #@'   ;@ @+      @ .@ :@@@@@@                                        @@@")
    print("@@@                                                                                              @@@")
    print("@@@                                                                                              @@@")
    print("@@@                                                                                              @@@")
    print("@@@                                                                                              @@@")
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print("@@@                                                                                              @@@")
    print("@@@                                                                                              @@@")

def Color_Mail():
    print(Green_Blackxx + "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" + Reset)
    print(Green_Blackxx + "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" + Reset)
    print(Green_Blackxx + "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" + Reset)
    print(Green_Blackxx + "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" + Reset)
    print(Green_Blackxx + "@@@                                                                                              @@@" + Reset)
    print(Green_Blackxx + "@@@                                                                                              @@@" + Reset)
    print(Green_Blackxx + "@@@" + Red_Blackxxxx + "  @          @; `@@@@@@@  `@@@@@@@@ ;@      @; @@@@@@@@                                       " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + Red_Blackxxxx + "  @@        @@+ @@:::::@@ @@::::::: ;@      @; @:::::::                                       " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + Red_Blackxxxx + "  @@@      @@@+ @      ;@ @# @@@@@@ ;@      @; @::::::                                        " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + Red_Blackxxxx + "  @ @@    @@ @+ @::::::+@ @# @@@@@@ ;@      @; @@@@@@@@.          " + Yellow_Blackx + "@@@@@@@@@@@@@@@@@@          " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + Red_Blackxxxx + "  @  @@  @@  @+ @@@@@@@@@ @#      @ ;@      @;        @#         " + Yellow_Blackx + "` @@@@@@@@@@@@@@@@           " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + Red_Blackxxxx + "  @   @@#@   @+ @      ;@ @#      @ ;@      @;        @#         " + Yellow_Blackx + "@` #@@@@@@@@@@@@@  @         " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + Red_Blackxxxx + "  @    @@    @+ @      ;@ +@@@@@@@@  @@@@@@@@  @@@@@@@@`         " + Yellow_Blackx + "@@: '@@@@@@@@@@@  @@         " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + "                                                                 " + Yellow_Blackx + "@@@' '@@@@@@@@@  @@@         " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + "                                                                 " + Yellow_Blackx + "@@@@' :@@@@@@@  @@@@         " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + "                                                                 " + Yellow_Blackx + "@@@@@# `@@@@@  @@@@@         " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + "                                                                 " + Yellow_Blackx + "@@@@@@   @@@  `@@@@@         " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + "                                                                 " + Yellow_Blackx + "@@@@@  @ `@ `@ `@@@@         " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + White_Blackxx + "                    @;         #@  @@@@@@@. .@ :@                " + Yellow_Blackx + "@@@@  @@@  `@@@  @@@         " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + White_Blackxx + "                    @@:       +@@ @@:::::@@ .@ :@                " + Yellow_Blackx + "@@@  @@@@@:@@@@@  @@         " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + White_Blackxx + "                    @+@.     ;@+@ @+      @ .@ :@                " + Yellow_Blackx + "@@  @@@@@@@@@@@@@  @         " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + White_Blackxx + "                    @:;@`   :@.;@ @#::::::@ .@ :@                " + Yellow_Blackx + "@  @@@@@@@@@@@@@@@           " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + White_Blackxx + "                    @: +@` .@: ;@ @@@@@@@@@ .@ :@                 " + Yellow_Blackx + "`@@@@@@@@@@@@@@@@@          " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + White_Blackxx + "                    @:  +@`@:  ;@ @+      @ .@ :@                                             " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@" + White_Blackxx + "                    @:   #@'   ;@ @+      @ .@ :@@@@@@                                        " + Reset + Green_Blackxx + "@@@" + Reset)
    print(Green_Blackxx + "@@@                                                                                              @@@" + Reset)
    print(Green_Blackxx + "@@@                                                                                              @@@" + Reset)
    print(Green_Blackxx + "@@@                                                                                              @@@" + Reset)
    print(Green_Blackxx + "@@@                                                                                              @@@" + Reset)
    print(Green_Blackxx + "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" + Reset)
    print(Green_Blackxx + "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" + Reset)
    print(Green_Blackxx + "@@@                                                                                              @@@" + Reset)
    print(Green_Blackxx + "@@@                                                                                              @@@" + Reset)

def BURST_icon(): #displays info about burst
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       ;#       .@       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       `@@     @@@       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        @@@@@@@@@+       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       .@  @@@, #@       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       @@   @   @@`      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      +@@       @`@      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      @@@       @@@:     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    `@@;         `@@;    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@  ;@@@             @@@#  @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @@#           ,@@.   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     `@@@       +@@@     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      @;@       @ @      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       @@   `   @@;      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       +@  +@@  @@       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        @.@@.+@:@+       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        @@@@@@@@@@       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       ,@       @@       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       +         :       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")

def Color_Burst():
    print(Green_Blackxx, end='')
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@       " + Red_Blackxxxx + ";#       .@" + Green_Blackxx + "       @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@       " + Red_Blackxxxx + "`@@     @@@" + Green_Blackxx + "       @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@        " + Red_Blackxxxx + "@@@@@@@@@+" + Green_Blackxx + "       @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@       " + Red_Blackxxxx + ".@  @@@, #@" + Green_Blackxx + "       @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@       " + Red_Blackxxxx + "@@   @   @@`" + Green_Blackxx + "      @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@      " + Red_Blackxxxx + "+@@       @`@" + Green_Blackxx + "      @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@      " + Red_Blackxxxx + "@@@       @@@:" + Green_Blackxx + "     @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@    " + Red_Blackxxxx + "`@@;         `@@;" + Green_Blackxx + "    @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@  " + Red_Blackxxxx + ";@@@             @@@#" + Green_Blackxx + "  @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@    " + Red_Blackxxxx + "@@#           ,@@." + Green_Blackxx + "   @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@     " + Red_Blackxxxx + "`@@@       +@@@" + Green_Blackxx + "     @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@      " + Red_Blackxxxx + "@;@       @ @" + Green_Blackxx + "      @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@       " + Red_Blackxxxx + "@@   `   @@;" + Green_Blackxx + "      @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@       " + Red_Blackxxxx + "+@  +@@  @@" + Green_Blackxx + "       @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@        " + Red_Blackxxxx + "@.@@.+@:@+" + Green_Blackxx + "       @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@        " + Red_Blackxxxx + "@@@@@@@@@@" + Green_Blackxx + "       @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@       " + Red_Blackxxxx + ",@       @@" + Green_Blackxx + "       @", "     @@@@\n" + Reset)
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@       " + Red_Blackxxxx + "+         :" + Green_Blackxx + "       @", "     @@@@\n" + Reset)
    print(Green_Blackxx, end='')
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n" + Reset)

def NECROSIS_icon(): #Displays info about necrosis
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @@@           @@@    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   @. @'         @. @'   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   @  .@         @  .@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   @@.@.         @@.@.   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    '@.           '@.    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   `                '    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @              '`    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     @`           '@     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     ,@@         @@      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      @@@@     +@@;      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       @@,@@@@@:@@       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        +@`    @@        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@          @@@@@.         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")

def Color_Necrosis(): #Displays info about necrosis
    print(Green_Blackxx, end='')
    WordCore.word_corey(Green_Blackxx + "@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "        @@@@\n")
    WordCore.word_corey(Green_Blackxx + "@@@@  ", "@                         @", "        @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@    " + Yellow_Blackx + "@@@           @@@    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@   " + Yellow_Blackx + "@. @'         @. @'   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@   " + Yellow_Blackx + "@  .@         @  .@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@   " + Yellow_Blackx + "@@.@.         @@.@.   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@    " + Yellow_Blackx + "'@.           '@.    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey(Green_Blackxx + "@@@@  ", "@                         @", "        @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@   " + Blue_Blackxxx + "`                '    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@    " + Blue_Blackxxx + "@              '`    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@     " + Blue_Blackxxx + "@`           '@     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@     " + Blue_Blackxxx + ",@@         @@      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@      " + Blue_Blackxxx + "@@@@     +@@;      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@       " + Blue_Blackxxx + "@@,@@@@@:@@       " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@        " + Blue_Blackxxx + "+@`    @@        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@          " + Blue_Blackxxx + "@@@@@.         " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey(Green_Blackxx + "@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "        @@@@\n")
    print(Reset, end='')

def WATER_icon(): #Displays info about water
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        @+               @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@         @@              @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@         '@@             @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@          @+@            @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@          @ @.           @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@          @  @           @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@          @  ;@          @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@          @   @`         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@          @    @         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@         ++    @         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@         @     @`        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        ,# @@@ ;;        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        @  @ @ ;;        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        @  @ @ +,        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        @  ,@@ @         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        #+    .@         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@         @@@@@@          @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")

def Color_Water(): #Displays info about water
    print(Green_Blackxx, end='')
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "        @+               " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "         @@              " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "         '@@             " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "          @+@            " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "          @ @.           " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "          @  @           " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "          @  ;@          " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "          @   @`         " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "          @    @         " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "         ++    @         " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "         @     @`        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "        ,# @@@ ;;        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "        @  @ @ ;;        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "        @  @ @ +,        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "        @  ,@@ @         " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "        #+    .@         " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "         @@@@@@          " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey(Green_Blackxx + "@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "        @@@@\n")
    print(Reset, end='')

def AIR_icon(): #Displays info about air
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@          `'@+;          @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        #@@:`.'@@        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       @'       `@,      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     `@           @`     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     @             @     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @;     `@@@    @,    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @     +@  `@`   @    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   .@    `@ ;@  @   @    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   +.    @` @   @   @    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   @     @  @   @   @    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   @     @` @',@,  #:    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   @     `@  ;+    @     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   ':     @'      @`     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @      @@, .@@`      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @        +@+`        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    '+                   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     @                   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     `@                  @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      ,@                 @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       .@,               @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@         @@;             @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@           '@            @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")

def Color_Air(): #Displays info about air
    print(Green_Blackxx, end='')
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "          `'@+;          " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "        #@@:`.'@@        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "       @'       `@,      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "     `@           @`     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "     @             @     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "    @;     `@@@    @,    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "    @     +@  `@`   @    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "   .@    `@ ;@  @   @    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "   +.    @` @   @   @    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "   @     @  @   @   @    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "   @     @` @',@,  #:    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "   @     `@  ;+    @     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "   ':     @'      @`     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "    @      @@, .@@`      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "    @        +@+`        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "    '+                   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "     @                   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "     `@                  " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "      ,@                 " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "       .@,               " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "         @@;             " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Cyan_Blackxxx + "           '@            " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    print(Reset, end='')

def BLOOD_icon(): # Displays info about blood
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@ @                     ''@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@ '@                   '@ @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@  '@                 '@  @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   '@               '@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    '@             '@    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     '@'@       '@'@     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      '@         +@      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@  '                   '  @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@  '@                 '@  @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   '@               '@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    '@             '@    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     '@           '@     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      '@ @     @ '@      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       '@'      @@       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   '    :            '   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   '@               '@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    '@             '@    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     '@           '@     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      '@         '@      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       '@ @   @ '@       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        '@'    @@        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@         ,               @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")

def Color_Blood(): # Displays info about blood
    print(Green_Blackxx, end='')
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + " @                     ''" + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + " '@                   '@ " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "  '@                 '@  " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "   '@               '@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "    '@             '@    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "     '@'@       '@'@     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "      '@         +@      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "  '                   '  " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "  '@                 '@  " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "   '@               '@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "    '@             '@    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "     '@           '@     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "      '@ @     @ '@      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "       '@'      @@       " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "   '    :            '   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "   '@               '@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "    '@             '@    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "     '@           '@     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "      '@         '@      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "       '@ @   @ '@       " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "        '@'    @@        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "         ,               " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    print(Reset, end='')

def SALIVA_icon(): # Shows saliva info
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@  '`                 `'  @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   @'               .@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @@`            @@    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      @@,        +@;     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      @ #@@@@@@@@;@      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      @     @     @      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      ';    @     @      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       @    @    :+      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@  @#   @    @    @   +@  @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   #@  #'   @   .@  @@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    `@@ @   @   @ .@'    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      ,@@@, @ ,@'@@      @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@         +@@@@@@;        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")

def Color_Saliva(): # Shows saliva info
    print(Green_Blackxx, end='')
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "  '`                 `'  " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "   @'               .@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "    @@`            @@    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "      @@,        +@;     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "      @ #@@@@@@@@;@      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Magenta_Black + "      @     @     @      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Magenta_Black + "      ';    @     @      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Magenta_Black + "       @    @    :+      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Magenta_Black + "  @#   @    @    @   +@  " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Magenta_Black + "   #@  #'   @   .@  @@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Magenta_Black + "    `@@ @   @   @ .@'    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "      ,@@@, @ ,@'@@      " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Blue_Blackxxx + "         +@@@@@@;        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    print(Reset, end='')

def ZOMBIFY_icon(): # Explains what zombify is
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   @'  .@       @@@@.    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @';@       @:   @    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@     @@        @    @    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @@@'       @    @    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    +  @'      '@  :@    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                '@@@     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@  ,'                 '   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   @@               @@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   @+@`            @#@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   ;+.@@`        @@`@    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @@  @@@#++@@@.@;@    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    @:  @ @..@.@   @;    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        '@    @@         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@         ,    :@         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")

def Color_Zombify(): # Explains what zombify is
    print(Green_Blackxx, end='')
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Green_Blackxx + "   @'  .@       @@@@.    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Green_Blackxx + "    @';@       @:   @    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Green_Blackxx + "     @@        @    @    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Green_Blackxx + "    @@@'       @    @    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Green_Blackxx + "    +  @'      '@  :@    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Green_Blackxx + "                '@@@     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "  ,'                 '   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "   @@               @@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "   @+@`            @#@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "   ;+.@@`        @@`@    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "    @@  @@@#++@@@.@;@    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "    @:  @ @..@.@   @;    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "        '@    @@         " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + Red_Blackxxxx + "         ,    :@         " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    print(Reset, end='')

def RISE_icon(): # more info
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                 .       @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@              @@@+@@     @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@            @@.    `@    @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@           @'.      @.   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@          @,  ,      @   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@         @'   @      @   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@        @'#   ,@     @   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@       @;  ;   @;    @   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@      @,   @   ,@@   @   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    `@`    '@   @`@@'@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@    `@`    '@   @`@@'@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@   .@@@@@#  @,  @   '@   @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@  ,@+    @+ @@. @        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@          @@@ @@+        @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@           `             @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")

def Color_Rise(): # more info
    print(Green_Blackxx, end='')
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@                         @", "@@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "                 .       " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "              @@@+@@     " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "            @@.    `@    " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "           @'.      @.   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "          @,  ,      @   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "         @'   @      @   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "        @'#   ,@     @   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "       @;  ;   @;    @   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "      @,   @   ,@@   @   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "    `@`    '@   @`@@'@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "    `@`    '@   @`@@'@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "   .@@@@@#  @,  @   '@   " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "  ,@+    @+ @@. @        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey_c(Green_Blackxx + "@@@@  ", "@" + White_Blackxx + "          @@@ @@+        " + Green_Blackxx + "@", "     @@@@\n")
    WordCore.word_corey("@@@@  ", "@           `             @", "@@@@\n")
    WordCore.word_corey("@@@@  ", "@@@@@@@@@@@@@@@@@@@@@@@@@@@", "@@@@\n")
    print(Reset, end='')

def infected_game_over_icon():
    WordCore.word_core("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n", 0.01)
    WordCore.word_core("{      _____       ___     _     _    _____     ____     _      _   _____   ___     }\n", 0.01)
    WordCore.word_core("{    //-----\\\\    //-\\\\   | \   / |  ||----   //    \\\\  \ \    / / ||----  || \\\\    }\n", 0.01)
    WordCore.word_core("{    ||          //   \\\\  | \\\\_// |  ||____   || || ||   \ \  / /  ||____  ||_//    }\n", 0.01)
    WordCore.word_core("{    ||  _____   ||---||  | |   | |  ||----   || || ||    \ \/ /   ||----  || \\\\    }\n", 0.01)
    WordCore.word_core("{    \\\\_____//   ||   ||  |_|   |_|  ||____   \\\\____//     \__/    ||____  ||  \\\\   }\n", 0.01)
    print("{	                                                                            }")
    WordCore.word_core("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n", 0.01)

def color_infected_game_over_icon():
    print(Red_Whitexxxx, end='')
    WordCore.word_core(Red_Whitexxxx + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n", 0.01) ; print(Red_Whitexxxx, end='')
    WordCore.word_core(Red_Whitexxxx + "{      _____       ___     _     _    _____     ____     _      _   _____   ___     }\n", 0.01)
    WordCore.word_core(Red_Whitexxxx + "{    //-----\\\\    //-\\\\   | \   / |  ||----   //    \\\\  \ \    / / ||----  || \\\\    }\n", 0.01)
    WordCore.word_core(Red_Whitexxxx + "{    ||          //   \\\\  | \\\\_// |  ||____   || || ||   \ \  / /  ||____  ||_//    }\n", 0.01)
    WordCore.word_core(Red_Whitexxxx + "{    ||  _____   ||---||  | |   | |  ||----   || || ||    \ \/ /   ||----  || \\\\    }\n", 0.01)
    WordCore.word_core(Red_Whitexxxx + "{    \\\\_____//   ||   ||  |_|   |_|  ||____   \\\\____//     \__/    ||____  ||  \\\\   }\n", 0.01)
    print(Red_Whitexxxx + "{	                                                                            }")
    WordCore.word_core(Red_Whitexxxx + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n", 0.01)
    print(Reset, end='')

#def cured_game_over_icon(): # You got cured
#    WordCore.word_core("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n", 0.01)
#    WordCore.word_core("{      _____       ___     _     _    _____     ____     _      _   _____   ___     }\n", 0.01)
#    WordCore.word_core("{    //-----\\\\    //-\\\\   | \   / |  ||----   //    \\\\  \ \    / / ||----  || \\\\    }\n", 0.01)
#    WordCore.word_core("{    ||          //   \\\\  | \\\\_// |  ||____   || || ||   \ \  / /  ||____  ||_//    }\n", 0.01)
#    WordCore.word_core("{    ||  _____   ||---||  | |   | |  ||----   || || ||    \ \/ /   ||----  || \\\\    }\n", 0.01)
#    WordCore.word_core("{    \\\\_____//   ||   ||  |_|   |_|  ||____   \\\\____//     \__/    ||____  ||  \\\\   }\n", 0.01)
#    print("{	                                                                            }")
#    WordCore.word_core("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n", 0.01)

def victory_icon(): # Everyone dies
    WordCore.word_core("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;';;;;;;;';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;#;;;;;;;;;;;;;+';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@';;;;;;;;;;;;;;;;#+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;#@;;;;;;;;;;;;;;;;;;;'@';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@#;;;;;;;;;;;;;;;;;;;;;;@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'@#;;;;;;;;;;;;;;;;;;;;;;;;@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;'@@;;;;;;;;;;;;;;;;;;;;;;;;;'@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@;;;;;;;;;;;;;;;;;;;;;;;;;;;#@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+@@';;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;+@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@+;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;+@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+@@@;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@+;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;#@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@';;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@#;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;'@@@@@;;;;;;;;;;;;;'+++';;;;;;;;;;;;;#@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;'@@@@@+;;;;;;;;+@@@@@@@@@@@@;;;;;;;;;@@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;'@@@@@@;;;;;;@@@@@@@@@@@@@@@@@+;;;;;;@@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@@;;;;#@@@@@@@@@@@@@@@@@@@@';;;@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@;;@@@@@@@@@@@@@@@@@@@@@@@+;;@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@+;;@@@@@@@@@#+##@@@@@@@@@;;@@@@@@@+;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@@;;'@@@@+;;;;;;;;;;#@@@@;;@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;+@@@@@@@@;;;@';;;;;;;;;;;;;;##;;#@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@@@;;;;;;;;;;;;;;;;;;;;;#@@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;#@@@@@@@@@@@+;;;;;;;;;;;;;;;;;;@@@@@@@@@@#+;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;#@@@@@@@@@@@@@@@@;;;;;;;;;;;;;;;+@@@@@@@@@@@@@@@#;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;@@@@@@@@@@@@@@@@@@@@@+;;;;;;;;;;#@@@@@@@@@@@@@@@@@@@@';;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;#@@@@@@@@@@@@@@@@@@@@@@@@@@#;'@@@@@@@@@@@@@@@@@@@@@@@@@@@;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;'@@@@@@@@@@@@@@@@@@@@@@@@@@@@';;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;@@@@@@@@@#+++#@@@@@@@@@@@@@@@@;;;;;'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;@@@@@@@;;;;;;;;;;;+@@@@@@@@@@@;;;;;;;'@@@@@@@@@@@#;;;;;;;;;'@@@@@@@';;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;#@@@@@;;;;;;;;;#+;;;;'@@@@@@@@';;;;;;;;@@@@@@@@@+;;;;;';;;;;;;;#@@@@@;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;@@@@';;;;;;;;;;@@@@#;;;@@@@@@@;;;;;;;;;'@@@@@@@;;;+@@@@;;;;;;;;;;@@@@@;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;@@@@;;;;;;;;;;;;@@@@@;;;;+@@@@@;;;;;;;;;;@@@@@+;;;;@@@@@;;;;;;;;;;;#@@@;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;@@@;;;;;;;;;;;;;@@@@@;;;;;+@@@@;;;;;;;;;'@@@@';;;;;@@@@@;;;;;;;;;;;;#@@@;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;#@@;;;;;;;;;;;;;;@@@@@;;;;;;#@@#;;;;;;;;;;@@@+;;;;;;@@@@@;;;;;;;;;;;;;#@@;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;@@';;;;;;;;;;;;;;@@@@@;;;;;;;@;;;;;;;;;;;;;'@;;;;;;'@@@@@;;;;;;;;;;;;;;@@#;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;@@;;;;;;;;;;;;;;;@@@@@;;;;;;;;;;@@;;;;;'@#;;;;;;;;;#@@@@#;;;;;;;;;;;;;;;@@;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;+@;;;;;;;;;;;;;;;;#@@@@#;;;;;;;#@@@@@##@@@@@';;;;;;;@@@@@;;;;;;;;;;;;;;;;@@;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;@@;;;;;;;;;;;;;;;;;@@@@@;;;;;;;;@@@@@@@@@@@@;;;;;;;;@@@@@;;;;;;;;;;;;;;;;;@;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;@';;;;;;;;;;;;;;;;;@@@@@+;;;;;;;@@@@@@@@@@@#;;;;;;;@@@@@@;;;;;;;;;;;;;;;;;@+;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;@;;;;;;;;;;;;;;;;;;#@@@@@;;;;;;;#@@@@@@@@@@;;;;;;;;@@@@@';;;;;;;;;;;;;;;;;+#;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;@;;;;;;;;;;;;;;;;;;;@@@@@@;;;;;;'@@@@@@@@@@;;;;;;;@@@@@@;;;;;;;;;;;;;;;;;;;@;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;@;;;;;;;;;;;;;;;;;;;#@@@@@#;;;;;;@@@@@@@@@@;;;;;;@@@@@@';;;;;;;;;;;;;;;;;;;@;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;#;;;;;;;;;;;;;;;;;;;;@@@@@@+;;;;;@@@@@@@@@@;;;;;#@@@@@@;;;;;;;;;;;;;;;;;;;;@;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;#;;;;;;;;;;;;;;;;;;;;;@@@@@@#;;;;@@@@@@@@@@;;;;@@@@@@@;;;;;;;;;;;;;;;;;;;;;#;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;#;;;;;;;;;;;;;;;;;;;;;+@@@@@@@';;@@@@@@@@@@;;;@@@@@@@';;;;;;;;;;;;;;;;;;;;;+;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;#;;;;;;;;;;;;;;;;;;;;;;+@@@@@@@;;@@@@@@@@@@;'@@@@@@@+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+@@@@@@;;@@@@@@@@@@;;@@@@@@+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'@@@@#;+@@@@@@@@@@;;@@@@@';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@;;@@@@@@@@@@@';@@@@;;;;;;;;;;;;;;;;;;;;;;;;;';;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@;;@@@@@@@@@@@@;;@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;#@@@@@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@@@@@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'@@@@@@@@@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@@+@@@@@@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;';;;;;;;;;;;;;;;;;;;;;;@@@@@@@@#;;@@@@@@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;';;;;;;;;;;;;;;;;;;;+@@@@@@@@#;;;'@@@@@@@@@;;;;;;;;;;;;;;;;;;;;';;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;'+;;;;;;;;;;;;;;;;@@@@@@@@@+;;;;;;@@@@@@@@@;;;;;;;;;;;;;;;;;';;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;@+;;;;;;;;;;;;#@@@@@@@@@';;;;;;;;@@@@@@@@@@;;;;;;;;;;;;;'@;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;'@@+;;;;;'#@@@@@@@@@@#;;;;;;;;;;;'@@@@@@@@@@+;;;;;;;;#@+;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;'@@@@@@@@@@@@@@@@#;;;;;;;;;;;;;;;+@@@@@@@@@@@@@@@@@+;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;+@@@@@@@@@@#;;;;;;;;;;;;;;;;;;;;;@@@@@@@@@@@@@';;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'+++';;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n", 0.001)
    print("\n")
    WordCore.word_core("  +@@         @@.@@    @@@@@@@@@@ @@@@@@@@@@@@   @@@@@@@@:   @@@@@@@@@@.  @@        #@`\n", 0.001)
    WordCore.word_core("   @@.       #@# @@  :@@@@@@@@@@@ @@@@@@@@@@@@ :@@@@@@@@@@@  @@@@@@@@@@@# @@        #@`\n", 0.001)
    WordCore.word_core("    @@       @@  @@  @@:               @@      @@:       @@  @@       `@@ @@        #@`\n", 0.001)
    WordCore.word_core("    #@#     @@.  @@  @@                @@      @@        @@  @@        @@ @@        #@`\n", 0.001)
    WordCore.word_core("     @@    :@@   @@  @@                @@      @@        @@  @@        @@ @@        #@`\n", 0.001)
    WordCore.word_core("     `@@   @@    @@  @@                @@      @@        @@  @@@@@@@@@@@@ +@@@@@@@@@@@`\n", 0.001)
    WordCore.word_core("      @@; @@:    @@  @@                @@      @@        @@  @@@@@@@@@@@   @@@@@@@@@@@`\n", 0.001)
    WordCore.word_core("       @@`@@     @@  @@                @@      @@        @@  @@   @@@               #@`\n", 0.001)
    WordCore.word_core("       ,@@@      @@  @@@@@@@@@@@@      @@      @@@@@@@@@@@@  @@    #@@'     @@@@@@@@@@\n", 0.001)
    WordCore.word_core("        @@'      @@   @@@@@@@@@@@      @@       @@@@@@@@@@#  @@     `@@@    @@@@@@@@@@\n", 0.001)
    print("\n")

def color_victory(): # Everyone dies
    print(Red_Blackxxxx, end='')
    WordCore.word_core("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;';;;;;;;';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;#;;;;;;;;;;;;;+';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@';;;;;;;;;;;;;;;;#+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;#@;;;;;;;;;;;;;;;;;;;'@';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@#;;;;;;;;;;;;;;;;;;;;;;@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'@#;;;;;;;;;;;;;;;;;;;;;;;;@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;'@@;;;;;;;;;;;;;;;;;;;;;;;;;'@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@;;;;;;;;;;;;;;;;;;;;;;;;;;;#@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+@@';;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;+@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@+;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;+@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+@@@;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@+;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;#@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@';;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@#;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;'@@@@@;;;;;;;;;;;;;'+++';;;;;;;;;;;;;#@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;'@@@@@+;;;;;;;;+@@@@@@@@@@@@;;;;;;;;;@@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;'@@@@@@;;;;;;@@@@@@@@@@@@@@@@@+;;;;;;@@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@@;;;;#@@@@@@@@@@@@@@@@@@@@';;;@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@;;@@@@@@@@@@@@@@@@@@@@@@@+;;@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@+;;@@@@@@@@@#+##@@@@@@@@@;;@@@@@@@+;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@@;;'@@@@+;;;;;;;;;;#@@@@;;@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;+@@@@@@@@;;;@';;;;;;;;;;;;;;##;;#@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@@@;;;;;;;;;;;;;;;;;;;;;#@@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;#@@@@@@@@@@@+;;;;;;;;;;;;;;;;;;@@@@@@@@@@#+;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;#@@@@@@@@@@@@@@@@;;;;;;;;;;;;;;;+@@@@@@@@@@@@@@@#;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;@@@@@@@@@@@@@@@@@@@@@+;;;;;;;;;;#@@@@@@@@@@@@@@@@@@@@';;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;#@@@@@@@@@@@@@@@@@@@@@@@@@@#;'@@@@@@@@@@@@@@@@@@@@@@@@@@@;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;'@@@@@@@@@@@@@@@@@@@@@@@@@@@@';;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;@@@@@@@@@#+++#@@@@@@@@@@@@@@@@;;;;;'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;@@@@@@@;;;;;;;;;;;+@@@@@@@@@@@;;;;;;;'@@@@@@@@@@@#;;;;;;;;;'@@@@@@@';;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;#@@@@@;;;;;;;;;#+;;;;'@@@@@@@@';;;;;;;;@@@@@@@@@+;;;;;';;;;;;;;#@@@@@;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;@@@@';;;;;;;;;;@@@@#;;;@@@@@@@;;;;;;;;;'@@@@@@@;;;+@@@@;;;;;;;;;;@@@@@;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;@@@@;;;;;;;;;;;;@@@@@;;;;+@@@@@;;;;;;;;;;@@@@@+;;;;@@@@@;;;;;;;;;;;#@@@;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;@@@;;;;;;;;;;;;;@@@@@;;;;;+@@@@;;;;;;;;;'@@@@';;;;;@@@@@;;;;;;;;;;;;#@@@;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;#@@;;;;;;;;;;;;;;@@@@@;;;;;;#@@#;;;;;;;;;;@@@+;;;;;;@@@@@;;;;;;;;;;;;;#@@;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;@@';;;;;;;;;;;;;;@@@@@;;;;;;;@;;;;;;;;;;;;;'@;;;;;;'@@@@@;;;;;;;;;;;;;;@@#;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;@@;;;;;;;;;;;;;;;@@@@@;;;;;;;;;;@@;;;;;'@#;;;;;;;;;#@@@@#;;;;;;;;;;;;;;;@@;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;+@;;;;;;;;;;;;;;;;#@@@@#;;;;;;;#@@@@@##@@@@@';;;;;;;@@@@@;;;;;;;;;;;;;;;;@@;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;@@;;;;;;;;;;;;;;;;;@@@@@;;;;;;;;@@@@@@@@@@@@;;;;;;;;@@@@@;;;;;;;;;;;;;;;;;@;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;@';;;;;;;;;;;;;;;;;@@@@@+;;;;;;;@@@@@@@@@@@#;;;;;;;@@@@@@;;;;;;;;;;;;;;;;;@+;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;@;;;;;;;;;;;;;;;;;;#@@@@@;;;;;;;#@@@@@@@@@@;;;;;;;;@@@@@';;;;;;;;;;;;;;;;;+#;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;@;;;;;;;;;;;;;;;;;;;@@@@@@;;;;;;'@@@@@@@@@@;;;;;;;@@@@@@;;;;;;;;;;;;;;;;;;;@;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;@;;;;;;;;;;;;;;;;;;;#@@@@@#;;;;;;@@@@@@@@@@;;;;;;@@@@@@';;;;;;;;;;;;;;;;;;;@;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;#;;;;;;;;;;;;;;;;;;;;@@@@@@+;;;;;@@@@@@@@@@;;;;;#@@@@@@;;;;;;;;;;;;;;;;;;;;@;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;#;;;;;;;;;;;;;;;;;;;;;@@@@@@#;;;;@@@@@@@@@@;;;;@@@@@@@;;;;;;;;;;;;;;;;;;;;;#;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;#;;;;;;;;;;;;;;;;;;;;;+@@@@@@@';;@@@@@@@@@@;;;@@@@@@@';;;;;;;;;;;;;;;;;;;;;+;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;#;;;;;;;;;;;;;;;;;;;;;;+@@@@@@@;;@@@@@@@@@@;'@@@@@@@+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+@@@@@@;;@@@@@@@@@@;;@@@@@@+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'@@@@#;+@@@@@@@@@@;;@@@@@';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@;;@@@@@@@@@@@';@@@@;;;;;;;;;;;;;;;;;;;;;;;;;';;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@;;@@@@@@@@@@@@;;@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;#@@@@@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@@@@@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'@@@@@@@@@@@@@@@@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@@@@@@@@+@@@@@@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;';;;;;;;;;;;;;;;;;;;;;;@@@@@@@@#;;@@@@@@@@#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;';;;;;;;;;;;;;;;;;;;+@@@@@@@@#;;;'@@@@@@@@@;;;;;;;;;;;;;;;;;;;;';;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;'+;;;;;;;;;;;;;;;;@@@@@@@@@+;;;;;;@@@@@@@@@;;;;;;;;;;;;;;;;;';;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;@+;;;;;;;;;;;;#@@@@@@@@@';;;;;;;;@@@@@@@@@@;;;;;;;;;;;;;'@;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;'@@+;;;;;'#@@@@@@@@@@#;;;;;;;;;;;'@@@@@@@@@@+;;;;;;;;#@+;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;'@@@@@@@@@@@@@@@@#;;;;;;;;;;;;;;;+@@@@@@@@@@@@@@@@@+;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;+@@@@@@@@@@#;;;;;;;;;;;;;;;;;;;;;@@@@@@@@@@@@@';;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'+++';;;;;;;;;;;;;;;;;;;;;;;;;@\n", 0.001)
    WordCore.word_core("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n", 0.001)
    print("\n")
    WordCore.word_core("  +@@         @@.@@    @@@@@@@@@@ @@@@@@@@@@@@   @@@@@@@@:   @@@@@@@@@@.  @@        #@`\n", 0.001)
    WordCore.word_core("   @@.       #@# @@  :@@@@@@@@@@@ @@@@@@@@@@@@ :@@@@@@@@@@@  @@@@@@@@@@@# @@        #@`\n", 0.001)
    WordCore.word_core("    @@       @@  @@  @@:               @@      @@:       @@  @@       `@@ @@        #@`\n", 0.001)
    WordCore.word_core("    #@#     @@.  @@  @@                @@      @@        @@  @@        @@ @@        #@`\n", 0.001)
    WordCore.word_core("     @@    :@@   @@  @@                @@      @@        @@  @@        @@ @@        #@`\n", 0.001)
    WordCore.word_core("     `@@   @@    @@  @@                @@      @@        @@  @@@@@@@@@@@@ +@@@@@@@@@@@`\n", 0.001)
    WordCore.word_core("      @@; @@:    @@  @@                @@      @@        @@  @@@@@@@@@@@   @@@@@@@@@@@`\n", 0.001)
    WordCore.word_core("       @@`@@     @@  @@                @@      @@        @@  @@   @@@               #@`\n", 0.001)
    WordCore.word_core("       ,@@@      @@  @@@@@@@@@@@@      @@      @@@@@@@@@@@@  @@    #@@'     @@@@@@@@@@\n", 0.001)
    WordCore.word_core("        @@'      @@   @@@@@@@@@@@      @@       @@@@@@@@@@#  @@     `@@@    @@@@@@@@@@\n", 0.001)
    print(Reset, end='')

def lux():
    WordCore.word_corez("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
    WordCore.word_corez("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@ +@@@         #@@#                                                  @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@  `@@@       @@@.                                                   @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@    @@@.   `@@@                                                     @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@     #@@# +@@@                                                      @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@      .@@@@@:                                                       @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@        @@@`                                                        @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@      .@@@@@'                                                       @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@     #@@+ :@@@                                                      @@@@\n")
    WordCore.word_corez("@@@@ @@        `@@        :@@    @@@.    @@@                                                     @@@@\n")
    WordCore.word_corez("@@@@ @@@@@@@@@@ @@@@@@@@@@@@#  .@@@       @@@;                                                   @@@@\n")
    WordCore.word_corez("@@@@ @@@@@@@@@@ `@@@@@@@@@@#  +@@@         '@@@                                                  @@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    WordCore.word_corez("@@@@                                                :     # @@@@@@@@@ +@@@@@@@@ #     :          @@@@\n")
    WordCore.word_corez("@@@@                                               @@   :@@ @:     :@ @@        @@:   @@         @@@@\n")
    WordCore.word_corez("@@@@                                             #@+   @@.  @:     .@ #@@@@@@@`  .@@   +@#       @@@@\n")
    WordCore.word_corez("@@@@                                             @;   #@`   @:     .@  ;@@@@@@@   `@#   ;@       @@@@\n")
    WordCore.word_corez("@@@@                                              @@:  :@@  @:     .@        `@  @@:  :@@        @@@@\n")
    WordCore.word_corez("@@@@                                               :@    #@ @@:::::@@ :::::::#@ @#    @:         @@@@\n")
    WordCore.word_corez("@@@@                                                        :@@@@@@@: @@@@@@@@'                  @@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    WordCore.word_corez("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
    WordCore.word_corez("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")

def Color_lux():
    print(Green_Blackxx, end='')
    WordCore.word_corez("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
    WordCore.word_corez("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@ +@@@         #@@#                                                  @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@  `@@@       @@@.                                                   @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@    @@@.   `@@@                                                     @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@     #@@# +@@@                                                      @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@      .@@@@@:                                                       @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@        @@@`                                                        @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@      .@@@@@'                                                       @@@@\n")
    WordCore.word_corez("@@@@ @@        .@@         @@     #@@+ :@@@                                                      @@@@\n")
    WordCore.word_corez("@@@@ @@        `@@        :@@    @@@.    @@@                                                     @@@@\n")
    WordCore.word_corez("@@@@ @@@@@@@@@@ @@@@@@@@@@@@#  .@@@       @@@;                                                   @@@@\n")
    WordCore.word_corez("@@@@ @@@@@@@@@@ `@@@@@@@@@@#  +@@@         '@@@                                                  @@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    WordCore.word_corez("@@@@                                                :     # @@@@@@@@@ +@@@@@@@@ #     :          @@@@\n")
    WordCore.word_corez("@@@@                                               @@   :@@ @:     :@ @@        @@:   @@         @@@@\n")
    WordCore.word_corez("@@@@                                             #@+   @@.  @:     .@ #@@@@@@@`  .@@   +@#       @@@@\n")
    WordCore.word_corez("@@@@                                             @;   #@`   @:     .@  ;@@@@@@@   `@#   ;@       @@@@\n")
    WordCore.word_corez("@@@@                                              @@:  :@@  @:     .@        `@  @@:  :@@        @@@@\n")
    WordCore.word_corez("@@@@                                               :@    #@ @@:::::@@ :::::::#@ @#    @:         @@@@\n")
    WordCore.word_corez("@@@@                                                        :@@@@@@@: @@@@@@@@'                  @@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    WordCore.word_corez("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
    WordCore.word_corez("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    WordCore.word_corez("@@@@                                                                                             @@@@\n")
    print(Reset, end='')

def player_menu_UI():
    WordCore.word_corey("@@@@", "  Week: " + str(week), "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> WORLD | ", "View world data", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> VIRUS | ", "View nano-virus data", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> LAB | ", "Work on your virus in the lab", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> TURN | ", "Move onto the next week", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> FAST | ", "Enter fast turn mode", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> SAVE | ", "Save your progress", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> LOAD | ", "Load a previous save", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> EXIT | ", "Quit the game without saving", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")

def Color_player_menu_UI():
    print(Green_Blackxx, end='')
    WordCore.word_corey("@@@@", "  Week: " + str(week), "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> WORLD | ", "View world data", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> VIRUS | ", "View nano-virus data", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> LAB | ", "Work on your virus in the lab", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> TURN | ", "Move onto the next week", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> FAST | ", "Enter fast turn mode", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> SAVE | ", "Save your progress", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> LOAD | ", "Load a previous save", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    WordCore.word_corey("@@@@ >>> EXIT | ", "Quit the game without saving", "@@@@\n")
    WordCore.word_corey("@@@@", "", "@@@@\n")
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print(Reset, end='')

#Color_Mail()
#lux_Color()
#Color_player_menu_UI()
#Color_Burst()
#BURST_icon()
#Color_Necrosis()
#Color_Water()
#Color_Air()
#Color_Blood()
##Color_Saliva()
#Color_Zombify()
#Color_Rise()
#color_victory()
#color_infected_game_over_icon()